version: 0.1.{build}
os: Visual Studio 2015
configuration: Debug
platform: ARM
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- cmd: >-
    node --version

    npm --version

    npm install -g taco

    npm install -g cordova

    npm install -g gulp

    npm install
build_script:
- cmd: >-
    taco platform remove windows

    taco platform add windows

    taco install-reqs windows

    taco plugin install

    taco build windows --arch=arm --debug

    taco build windows --arch=x64 --debug

    taco build windows --arch=x86 --debug
artifacts:
- path: platforms\windows\**\*.appx
