version: 0.1.{build}
os: Visual Studio 2015
configuration: Debug
platform: ARM
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- cmd: >-
    node --version

    npm --version

    npm install -g cordova

    npm install -g gulp

    npm install
build_script:
- cmd: >-
    cordova platform add windows

    cordova plugin install

    cordova build windows --arch=arm --debug

    cordova build windows --arch=x64 --debug

    cordova build windows --arch=x86 --debug
artifacts:
- path: platforms\windows\**\*.appx
